export interface IAstroObject {
	uid: string;
	name: string;
	astronomicalObjectType: AstroObjectTypes;
	location: {
		uid: string;
		name: string;
	};
}

enum AstroObjectTypes {
	PLANET = 'PLANET',
	D_CLASS_PLANET = 'D_CLASS_PLANET',
	H_CLASS_PLANET = 'H_CLASS_PLANET',
	GAS_GIANT_PLANET = 'GAS_GIANT_PLANET',
	K_CLASS_PLANET = 'K_CLASS_PLANET',
	L_CLASS_PLANET = 'L_CLASS_PLANET',
	M_CLASS_PLANET = 'M_CLASS_PLANET',
	Y_CLASS_PLANET = 'Y_CLASS_PLANET',
	ROGUE_PLANET = 'ROGUE_PLANET',
	ARTIFICIAL_PLANET = 'ARTIFICIAL_PLANET',
	ASTEROID = 'ASTEROID',
	ASTEROIDAL_MOON = 'ASTEROIDAL_MOON',
	ASTEROID_BELT = 'ASTEROID_BELT',
	BORG_SPATIAL_DESIGNATION = 'BORG_SPATIAL_DESIGNATION',
	CLUSTER = 'CLUSTER',
	COMET = 'COMET',
	CONSTELLATION = 'CONSTELLATION',
	GALAXY = 'GALAXY',
	MOON = 'MOON',
	M_CLASS_MOON = 'M_CLASS_MOON',
	NEBULA = 'NEBULA',
	PLANETOID = 'PLANETOID',
	D_CLASS_PLANETOID = 'D_CLASS_PLANETOID',
	QUADRANT = 'QUADRANT',
	QUASAR = 'QUASAR',
	STAR = 'STAR',
	STAR_SYSTEM = 'STAR_SYSTEM',
	SECTOR = 'SECTOR',
	REGION = 'REGION',
}
